#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/webserver

- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Configure Apache Virtual Host
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart Apache

- name: Ensure Apache is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes
